[package]
authors = ["@colinnielsen"]
compiler_version = "0.9.0"
name = "ecrecover"
notes = "AMDG"
type = "lib"

[dependencies]
array_helpers = { tag = "v0.1.0", git = "https://github.com/shubham-kanodia/noir-array-helpers" }
